# Generated by Django 4.2.3 on 2023-07-18 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_booking_booking_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='reservation_date',
        ),
    ]
