# Generated by Django 4.2.3 on 2023-07-18 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_booking_reservation_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='name',
            new_name='first_name',
        ),
    ]
