# Generated by Django 4.2.3 on 2023-07-18 23:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rename_name_booking_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='reservation_slot',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
